version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: food_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-examplepass}
      MYSQL_DATABASE: ${DB_NAME:-food_db}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3305:3306"

  kong:
    image: kong:3.4
    container_name: kongadmin
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file: .env
    environment:
      - SERVICE_PORT=8080
    volumes:
      - ./auth-service:/app
    working_dir: /app
    ports:
      - "9001:8080"
    depends_on:
      - db

  menu-service:
    build: ./menu-service
    container_name: menu-service
    env_file: .env
    environment:
      - SERVICE_PORT=8080
    volumes:
      - ./menu-service:/app
    working_dir: /app
    ports:
      - "9002:8080"
    depends_on:
      - db

  order-service:
    build: ./order-service
    container_name: order-service
    env_file: .env
    environment:
      - SERVICE_PORT=8080
    volumes:
      - ./order-service:/app
    working_dir: /app
    ports:
      - "9003:8080"
    depends_on:
      - db

volumes:
  db_data:
